language: python
python: 2.7
env:
  - TOX_ENV=py26-dj14
  - TOX_ENV=py27-dj14
  - TOX_ENV=py27-dj15
  - TOX_ENV=py27-dj16
  - TOX_ENV=py27-dj17
  - TOX_ENV=py27-dj18
  - TOX_ENV=py33-dj15
  - TOX_ENV=py33-dj16
  - TOX_ENV=py33-dj17
  - TOX_ENV=py33-dj18
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success: cd tests && coveralls
